services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:

# O volume `db_data` foi definido, mas não está sendo usado ativamente
# porque o volume `.:/app` já persiste o arquivo `escola.db` no diretório local.
# Ele está aqui como um exemplo de como você poderia isolar os dados do banco
# se não quisesse que o arquivo .db ficasse na sua pasta de código-fonte.